Upgrade Decidim to 0.25
gencat/participa pull request #342
Opened 2022-07-18 10:39 UTC by LauraJaimeC

#### :tophat: What? Why?
TODO

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

### :camera: Screenshots (optional)
![Description](URL)

2022-08-17 14:44 UTC, tramuntanal requested changes
Very good job here @LauraJaimeC !

This is a first check, we'll QA and see how this complex upgrade works. Please apply the following sugestions when you have the time.

2022-08-22 06:16 UTC, LauraJaimeC commented on .github/workflows/test.yml
> +  test-report:
😅

2022-08-22 06:25 UTC, LauraJaimeC commented on decidim-process-extended/app/decorators/decidim/participatory_processes/admin/copy_participatory_process_decorator.rb
> -      banner_image: @participatory_process.banner_image,
This change coming from Decidim: 

https://github.com/CodiTramuntana/decidim/blob/release/0.25-stable/decidim-participatory_processes/app/commands/decidim/participatory_processes/admin/copy_participatory_process.rb

2022-08-22 06:28 UTC, LauraJaimeC commented on decidim-process-extended/app/decorators/decidim/participatory_processes/admin/update_participatory_process_decorator.rb
> -      remove_banner_image: form.remove_banner_image,
This change also comes from Decidim but some code is missing here...i'll change it..

2022-08-22 07:58 UTC, LauraJaimeC commented on db/migrate/20190114123610_move_organization_fields_to_hero_content_block.decidim.rb
> +    # mount_uploader :homepage_image, ::Decidim::HomepageImageUploader
The reason:
![imagen](https://user-images.githubusercontent.com/75725233/185869775-ef98ad12-448c-4ce1-8846-057f3c8ed5e0.png)

2022-08-22 11:00 UTC, tramuntanal commented on bin/setup
> +  system! "bin/yarn"
this is still pending

2022-08-22 11:02 UTC, tramuntanal commented on db/migrate/20190114123610_move_organization_fields_to_hero_content_block.decidim.rb
> +    # mount_uploader :homepage_image, ::Decidim::HomepageImageUploader
ok, then..

2022-08-22 11:05 UTC, tramuntanal commented on decidim-process-extended/app/decorators/decidim/participatory_processes/admin/copy_participatory_process_decorator.rb
> -      banner_image: @participatory_process.banner_image,
ok, now I see there's a `copy_participatory_process_attachments` method in the original class

2022-08-22 11:14 UTC, tramuntanal approved these changes
Good job @LauraJaimeC !

2022-09-29 14:13 UTC, LauraJaimeC commented
Superseded by https://github.com/gencat/participa/pull/347

2022-09-29 14:13 UTC, closed without merging